#!/bin/sh
set -eu

APP_USER="${APP_USER:-app}"
APP_GROUP="${APP_GROUP:-app}"

is_strong_secret() {
  s="${1:-}"
  [ -n "$s" ] || return 1
  [ "${#s}" -ge 16 ] || return 1
  [ "$s" != "change-me" ] || return 1
  [ "$s" != "dev-secret-change-me" ] || return 1
  return 0
}

DATA_DIR="/app/data"
SECRET_FILE="${DATA_DIR}/session_secret.txt"

# Ensure data dir exists; if root, try to make it writable for APP_USER.
mkdir -p "$DATA_DIR" 2>/dev/null || true
if [ "$(id -u 2>/dev/null || echo 1)" = "0" ]; then
  chown "$APP_USER:$APP_GROUP" "$DATA_DIR" 2>/dev/null || true
fi

# If the user didn't provide a strong secret, reuse (or create) a persisted one in ./data.
if ! is_strong_secret "${SESSION_SECRET:-}"; then
  if [ -f "$SECRET_FILE" ]; then
    persisted="$(cat "$SECRET_FILE" 2>/dev/null | tr -d '\r\n' || true)"
    if is_strong_secret "$persisted"; then
      export SESSION_SECRET="$persisted"
      export SESSION_SECRET_AUTOGENERATED="true"
      export SESSION_SECRET_PERSISTED="true"
    fi
  fi

  if ! is_strong_secret "${SESSION_SECRET:-}"; then
    # Generate + persist (best-effort). Keep file private.
    umask 077
    secret="$(head -c 32 /dev/urandom | hexdump -v -e '/1 "%02x"')"
    export SESSION_SECRET="$secret"
    export SESSION_SECRET_AUTOGENERATED="true"
    export SESSION_SECRET_PERSISTED="false"
    if ( set -C; : >"$SECRET_FILE" ) 2>/dev/null; then
      printf "%s\n" "$secret" >"$SECRET_FILE" 2>/dev/null || true
      chmod 600 "$SECRET_FILE" 2>/dev/null || true
      export SESSION_SECRET_PERSISTED="true"
    fi
  fi
fi

# If started as root, drop privileges for the app process.
if [ "$(id -u 2>/dev/null || echo 1)" = "0" ]; then
  # Best-effort: ensure files under /app/data are owned by APP_USER (bind mounts may still override perms).
  chown -R "$APP_USER:$APP_GROUP" "$DATA_DIR" 2>/dev/null || true
  exec su-exec "$APP_USER:$APP_GROUP" "$@"
fi

exec "$@"
